#ifndef __ERRORS_H__
#define __ERRORS_H__

#define MODE_PRINT 1
#define MODE_NOT_PRINT 0
#define PASS 0
#define MTR_OK 0
#define ERR_WRONG_ACTION 1
#define ERR_READ_ACTION 2
#define ERR_TOO_MUCH_NONZERO 3
#define ERR_NONINTEGER 4
#define ERR_NONUINTEGER 5
#define ERR_MEMORY_ALLOCATION 6
#define ERR_WRONG_mtrES_SIZES 7
#define ERR_NONROW 8
#define ERR_NO_MTR 9
#define ERR_PRINT_FLAG_READ 10
#define ERR_WRONG_ELEMENT_PARAMETERS 11
#define ERR_EMPTY_MTR 12
#define ERR_WRONG_PERCENT 13

#endif
